### ISSUE TITLE
Subscription needed?

### ISSUE THREAD

**Issue by findthebug** [graiz/newsprint#4]
On the Visionect website, there is a note stating that a subscription is needed to use the display. I was curious about this and reached out to their support. They informed me that a subscription is required even for self-hosting.

Has anyone experienced whether this is true, or is there a way to bypass this requirement?

**Comment by graiz** [comment]
Yes. This is a disappointment and I've already noted to their leadership that this would likely be a major issue for any community support.  I've recommended an "app-store" approach where you could allow free apps and rev-share on any published projects but it doesn't sound like there is technical bandwidth to go in that direction.  I don't believe the device will brick as my hardware does not have a subscription but your mileage may vary.

**Comment by findthebug** [comment]
Hey Greg

Just finished my custom e ink display:  feel free to check here: https://colorbloks.com/eink

best marco
